#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace SmartSocial.Data
{
    /// <summary>
    /// Class representing SpGetChartsByReportXIDResult data.
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(SmartSocial.Data.SpGetChartsByReportXIDResult.Metadata))]
    public partial class SpGetChartsByReportXIDResult
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="SpGetChartsByReportXIDResult"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static SpGetChartsByReportXIDResult()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="SpGetChartsByReportXIDResult"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public SpGetChartsByReportXIDResult()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _idSmartchart;

        /// <summary>
        /// Gets or sets the IdSmartchart column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdSmartchart", Storage = "_idSmartchart", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int IdSmartchart
        {
            get { return _idSmartchart; }
            set
            {
                if (_idSmartchart != value)
                {
                    OnIdSmartchartChanging(value);
                    _idSmartchart = value;
                    OnIdSmartchartChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _chartName;

        /// <summary>
        /// Gets or sets the ChartName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ChartName", Storage = "_chartName", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string ChartName
        {
            get { return _chartName; }
            set
            {
                if (_chartName != value)
                {
                    OnChartNameChanging(value);
                    _chartName = value;
                    OnChartNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private Nullable<int> _chartOrder;

        /// <summary>
        /// Gets or sets the ChartOrder column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ChartOrder", Storage = "_chartOrder", DbType = "int")]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Nullable<int> ChartOrder
        {
            get { return _chartOrder; }
            set
            {
                if (_chartOrder != value)
                {
                    OnChartOrderChanging(value);
                    _chartOrder = value;
                    OnChartOrderChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _axisSeriesTitle;

        /// <summary>
        /// Gets or sets the AxisSeriesTitle column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "AxisSeriesTitle", Storage = "_axisSeriesTitle", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string AxisSeriesTitle
        {
            get { return _axisSeriesTitle; }
            set
            {
                if (_axisSeriesTitle != value)
                {
                    OnAxisSeriesTitleChanging(value);
                    _axisSeriesTitle = value;
                    OnAxisSeriesTitleChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _axisValuesTitle;

        /// <summary>
        /// Gets or sets the AxisValuesTitle column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "AxisValuesTitle", Storage = "_axisValuesTitle", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string AxisValuesTitle
        {
            get { return _axisValuesTitle; }
            set
            {
                if (_axisValuesTitle != value)
                {
                    OnAxisValuesTitleChanging(value);
                    _axisValuesTitle = value;
                    OnAxisValuesTitleChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _cssClasses;

        /// <summary>
        /// Gets or sets the CssClasses column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "CssClasses", Storage = "_cssClasses", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string CssClasses
        {
            get { return _cssClasses; }
            set
            {
                if (_cssClasses != value)
                {
                    OnCssClassesChanging(value);
                    _cssClasses = value;
                    OnCssClassesChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _htmlStyles;

        /// <summary>
        /// Gets or sets the HtmlStyles column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "HtmlStyles", Storage = "_htmlStyles", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string HtmlStyles
        {
            get { return _htmlStyles; }
            set
            {
                if (_htmlStyles != value)
                {
                    OnHtmlStylesChanging(value);
                    _htmlStyles = value;
                    OnHtmlStylesChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _chartTypeName;

        /// <summary>
        /// Gets or sets the ChartTypeName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ChartTypeName", Storage = "_chartTypeName", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 8)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string ChartTypeName
        {
            get { return _chartTypeName; }
            set
            {
                if (_chartTypeName != value)
                {
                    OnChartTypeNameChanging(value);
                    _chartTypeName = value;
                    OnChartTypeNameChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="IdSmartchart"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSmartchartChanging(int value);
        /// <summary>Called after <see cref="IdSmartchart"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSmartchartChanged();
        /// <summary>Called when <see cref="ChartName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChartNameChanging(string value);
        /// <summary>Called after <see cref="ChartName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChartNameChanged();
        /// <summary>Called when <see cref="ChartOrder"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChartOrderChanging(Nullable<int> value);
        /// <summary>Called after <see cref="ChartOrder"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChartOrderChanged();
        /// <summary>Called when <see cref="AxisSeriesTitle"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnAxisSeriesTitleChanging(string value);
        /// <summary>Called after <see cref="AxisSeriesTitle"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnAxisSeriesTitleChanged();
        /// <summary>Called when <see cref="AxisValuesTitle"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnAxisValuesTitleChanging(string value);
        /// <summary>Called after <see cref="AxisValuesTitle"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnAxisValuesTitleChanged();
        /// <summary>Called when <see cref="CssClasses"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCssClassesChanging(string value);
        /// <summary>Called after <see cref="CssClasses"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCssClassesChanged();
        /// <summary>Called when <see cref="HtmlStyles"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnHtmlStylesChanging(string value);
        /// <summary>Called after <see cref="HtmlStyles"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnHtmlStylesChanged();
        /// <summary>Called when <see cref="ChartTypeName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChartTypeNameChanging(string value);
        /// <summary>Called after <see cref="ChartTypeName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChartTypeNameChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="SpGetChartsByReportXIDResult"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="SpGetChartsByReportXIDResult"/> instance.</param>
        /// <returns>An instance of <see cref="SpGetChartsByReportXIDResult"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static SpGetChartsByReportXIDResult FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SpGetChartsByReportXIDResult));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as SpGetChartsByReportXIDResult;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="SpGetChartsByReportXIDResult"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="SpGetChartsByReportXIDResult"/> instance.</param>
        /// <returns>An instance of <see cref="SpGetChartsByReportXIDResult"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static SpGetChartsByReportXIDResult FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SpGetChartsByReportXIDResult));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as SpGetChartsByReportXIDResult;
            }
        }
        
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
