//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartType
    {
        public ChartType()
        {
            this.DataProviderXChartTypes = new HashSet<DataProviderXChartType>();
            this.SmartCharts = new HashSet<SmartChart>();
        }
    
        public int idChartType { get; set; }
        public string ChartTypeName { get; set; }
        public string StoredProcedureName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DataProviderXChartType> DataProviderXChartTypes { get; set; }
        public virtual ICollection<SmartChart> SmartCharts { get; set; }
    }
}
