//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartComment
    {
        public int IdComment { get; set; }
        public string IdUser { get; set; }
        public int IdSmartChart { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Message { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SmartChart SmartChart { get; set; }
    }
}
