//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataProviderXChartType
    {
        public int idDataProvider { get; set; }
        public int idChartType { get; set; }
        public string FileLoadFunctionName { get; set; }
    
        public virtual ChartType ChartType { get; set; }
        public virtual DataProvider DataProvider { get; set; }
    }
}
