//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesValue
    {
        public int idSeriesValue { get; set; }
        public Nullable<int> idChartSeries { get; set; }
        public Nullable<int> idDataType { get; set; }
        public string Value { get; set; }
        public Nullable<int> RowPosition { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual ChartSery ChartSery { get; set; }
    }
}
