//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDelivery
    {
        public ServiceDelivery()
        {
            this.SmartReports = new HashSet<SmartReport>();
        }
    
        public int idServiceDelivery { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public Nullable<int> IdServiceSubscription { get; set; }
        public string Insights { get; set; }
    
        public virtual ServiceSubscription ServiceSubscription { get; set; }
        public virtual ICollection<SmartReport> SmartReports { get; set; }
    }
}
