//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartChart
    {
        public SmartChart()
        {
            this.ChartComments = new HashSet<ChartComment>();
            this.ChartSeries = new HashSet<ChartSery>();
        }
    
        public int idSmartChart { get; set; }
        public Nullable<int> idSmartReport { get; set; }
        public string ChartName { get; set; }
        public string FileName { get; set; }
        public string Insights { get; set; }
        public Nullable<int> IdChartType { get; set; }
        public Nullable<int> IdDataProvider { get; set; }
        public string AxisSeriesTitle { get; set; }
        public string AxisValuesTitle { get; set; }
        public string CssClasses { get; set; }
        public string HtmlStyles { get; set; }
        public Nullable<int> ChartOrder { get; set; }
        public string SocialPostFilter { get; set; }
    
        public virtual ChartType ChartType { get; set; }
        public virtual ICollection<ChartComment> ChartComments { get; set; }
        public virtual ICollection<ChartSery> ChartSeries { get; set; }
        public virtual DataProvider DataProvider { get; set; }
        public virtual SmartReport SmartReport { get; set; }
    }
}
