//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocial.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartReport
    {
        public SmartReport()
        {
            this.SmartCharts = new HashSet<SmartChart>();
            this.SocialPosts = new HashSet<SocialPost>();
        }
    
        public int idSmartReport { get; set; }
        public Nullable<int> idServiceDelivery { get; set; }
        public string ReportName { get; set; }
        public string Insights { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> isTemplate { get; set; }
    
        public virtual ServiceDelivery ServiceDelivery { get; set; }
        public virtual ICollection<SmartChart> SmartCharts { get; set; }
        public virtual ICollection<SocialPost> SocialPosts { get; set; }
    }
}
