//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace SmartSocial.Services.V2.DataTransferObjects
{
    
    [DataContract(Name = "AspNetUserClaimDto", Namespace = "http://www.mavizontech.com/dto/" , IsReference = true) ]
    public partial class AspNetUserClaimDto
    {
         #region Primitive Properties
    	
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual string UserId
        {
     
    		
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (AspNetUser != null && AspNetUser.Id != value)
                    {
                        AspNetUser = null;
                    }
                    _userId = value;
                }
            }
        }
        private string _userId;
    	
    	[DataMember]
        public virtual string ClaimType
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual string ClaimValue
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual AspNetUserDto AspNetUser
        {
            get { return _aspNetUser; }
            set
            {
                if (!ReferenceEquals(_aspNetUser, value))
                {
                    var previousValue = _aspNetUser;
                    _aspNetUser = value;
                    FixupAspNetUser(previousValue);
                }
            }
        }
        private AspNetUserDto _aspNetUser;

        #endregion

        #region Association Fixup
    
        private void FixupAspNetUser(AspNetUserDto previousValue)
        {
            if (previousValue != null && previousValue.AspNetUserClaims.Contains(this))
            {
                previousValue.AspNetUserClaims.Remove(this);
            }
    
            if (AspNetUser != null)
            {
                if (!AspNetUser.AspNetUserClaims.Contains(this))
                {
                    AspNetUser.AspNetUserClaims.Add(this);
                }
                if (UserId != AspNetUser.Id)
                {
                    UserId = AspNetUser.Id;
                }
            }
        }

        #endregion

    }
}
