//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace SmartSocial.Services.V2.DataTransferObjects
{
    
    [DataContract(Name = "UsersXSubscriptionDto", Namespace = "http://www.mavizontech.com/dto/" , IsReference = true) ]
    public partial class UsersXSubscriptionDto
    {
         #region Primitive Properties
    	
    	[DataMember]
        public virtual int idSubscription
        {
     
    		
            get { return _idSubscription; }
            set
            {
                if (_idSubscription != value)
                {
                    if (ServiceSubscription != null && ServiceSubscription.idServiceSubscription != value)
                    {
                        ServiceSubscription = null;
                    }
                    _idSubscription = value;
                }
            }
        }
        private int _idSubscription;
    	
    	[DataMember]
        public virtual string idUser
        {
     
    		
            get { return _idUser; }
            set
            {
                if (_idUser != value)
                {
                    if (AspNetUser != null && AspNetUser.Id != value)
                    {
                        AspNetUser = null;
                    }
                    _idUser = value;
                }
            }
        }
        private string _idUser;
    	
    	[DataMember]
        public virtual Nullable<System.DateTime> DateCreated
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual AspNetUserDto AspNetUser
        {
            get { return _aspNetUser; }
            set
            {
                if (!ReferenceEquals(_aspNetUser, value))
                {
                    var previousValue = _aspNetUser;
                    _aspNetUser = value;
                    FixupAspNetUser(previousValue);
                }
            }
        }
        private AspNetUserDto _aspNetUser;
    
    	[DataMember]
        public virtual ServiceSubscriptionDto ServiceSubscription
        {
            get { return _serviceSubscription; }
            set
            {
                if (!ReferenceEquals(_serviceSubscription, value))
                {
                    var previousValue = _serviceSubscription;
                    _serviceSubscription = value;
                    FixupServiceSubscription(previousValue);
                }
            }
        }
        private ServiceSubscriptionDto _serviceSubscription;

        #endregion

        #region Association Fixup
    
        private void FixupAspNetUser(AspNetUserDto previousValue)
        {
            if (previousValue != null && previousValue.UsersXSubscriptions.Contains(this))
            {
                previousValue.UsersXSubscriptions.Remove(this);
            }
    
            if (AspNetUser != null)
            {
                if (!AspNetUser.UsersXSubscriptions.Contains(this))
                {
                    AspNetUser.UsersXSubscriptions.Add(this);
                }
                if (idUser != AspNetUser.Id)
                {
                    idUser = AspNetUser.Id;
                }
            }
        }
    
        private void FixupServiceSubscription(ServiceSubscriptionDto previousValue)
        {
            if (previousValue != null && previousValue.UsersXSubscriptions.Contains(this))
            {
                previousValue.UsersXSubscriptions.Remove(this);
            }
    
            if (ServiceSubscription != null)
            {
                if (!ServiceSubscription.UsersXSubscriptions.Contains(this))
                {
                    ServiceSubscription.UsersXSubscriptions.Add(this);
                }
                if (idSubscription != ServiceSubscription.idServiceSubscription)
                {
                    idSubscription = ServiceSubscription.idServiceSubscription;
                }
            }
        }

        #endregion

    }
}
