#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace SmartSocial.Data
{
    /// <summary>
    /// The class representing the dbo.AspNetUserRoles table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.AspNetUserRoles")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(SmartSocial.Data.AspNetUserRoles.Metadata))]
    [System.Data.Services.Common.DataServiceKey("UserId", "RoleId")]
    [System.Diagnostics.DebuggerDisplay("UserId: {UserId}, RoleId: {RoleId}")]
    public partial class AspNetUserRoles
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="AspNetUserRoles"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static AspNetUserRoles()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="AspNetUserRoles"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public AspNetUserRoles()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            _roleAspNetRoles = default(System.Data.Linq.EntityRef<AspNetRoles>);
            _userAspNetUsers = default(System.Data.Linq.EntityRef<AspNetUsers>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _userId;

        /// <summary>
        /// Gets or sets the UserId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "UserId", Storage = "_userId", DbType = "nvarchar(128) NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (_userAspNetUsers.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnUserIdChanging(value);
                    SendPropertyChanging("UserId");
                    _userId = value;
                    SendPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _roleId;

        /// <summary>
        /// Gets or sets the RoleId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RoleId", Storage = "_roleId", DbType = "nvarchar(128) NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    if (_roleAspNetRoles.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnRoleIdChanging(value);
                    SendPropertyChanging("RoleId");
                    _roleId = value;
                    SendPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<AspNetRoles> _roleAspNetRoles;

        /// <summary>
        /// Gets or sets the <see cref="AspNetRoles"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspNetRoles_AspNetUserRoles", Storage = "_roleAspNetRoles", ThisKey = "RoleId", OtherKey = "Id", IsForeignKey = true, DeleteRule = "CASCADE")]
        [System.Runtime.Serialization.DataMember(Order = 3, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public AspNetRoles RoleAspNetRoles
        {
            get { return (serializing && !_roleAspNetRoles.HasLoadedOrAssignedValue) ? null : _roleAspNetRoles.Entity; }
            set
            {
                AspNetRoles previousValue = _roleAspNetRoles.Entity;
                if (previousValue != value || _roleAspNetRoles.HasLoadedOrAssignedValue == false)
                {
                    OnRoleAspNetRolesChanging(value);
                    SendPropertyChanging("RoleAspNetRoles");
                    if (previousValue != null)
                    {
                        _roleAspNetRoles.Entity = null;
                        previousValue.RoleAspNetUserRolesList.Remove(this);
                    }
                    _roleAspNetRoles.Entity = value;
                    if (value != null)
                    {
                        value.RoleAspNetUserRolesList.Add(this);
                        _roleId = value.Id;
                    }
                    else
                    {
                        _roleId = default(string);
                    }
                    SendPropertyChanged("RoleAspNetRoles");
                    OnRoleAspNetRolesChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<AspNetUsers> _userAspNetUsers;

        /// <summary>
        /// Gets or sets the <see cref="AspNetUsers"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspNetUsers_AspNetUserRoles", Storage = "_userAspNetUsers", ThisKey = "UserId", OtherKey = "Id", IsForeignKey = true, DeleteOnNull = true, DeleteRule = "CASCADE")]
        [System.Runtime.Serialization.DataMember(Order = 4, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public AspNetUsers UserAspNetUsers
        {
            get { return (serializing && !_userAspNetUsers.HasLoadedOrAssignedValue) ? null : _userAspNetUsers.Entity; }
            set
            {
                AspNetUsers previousValue = _userAspNetUsers.Entity;
                if (previousValue != value || _userAspNetUsers.HasLoadedOrAssignedValue == false)
                {
                    OnUserAspNetUsersChanging(value);
                    SendPropertyChanging("UserAspNetUsers");
                    if (previousValue != null)
                    {
                        _userAspNetUsers.Entity = null;
                        previousValue.UserAspNetUserRolesList.Remove(this);
                    }
                    _userAspNetUsers.Entity = value;
                    if (value != null)
                    {
                        value.UserAspNetUserRolesList.Add(this);
                        _userId = value.Id;
                    }
                    else
                    {
                        _userId = default(string);
                    }
                    SendPropertyChanged("UserAspNetUsers");
                    OnUserAspNetUsersChanged();
                }
            }
        }
        
        
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="UserId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnUserIdChanging(string value);
        /// <summary>Called after <see cref="UserId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnUserIdChanged();
        /// <summary>Called when <see cref="RoleId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnRoleIdChanging(string value);
        /// <summary>Called after <see cref="RoleId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnRoleIdChanged();
        /// <summary>Called when <see cref="RoleAspNetRoles"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnRoleAspNetRolesChanging(AspNetRoles value);
        /// <summary>Called after <see cref="RoleAspNetRoles"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnRoleAspNetRolesChanged();
        /// <summary>Called when <see cref="UserAspNetUsers"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnUserAspNetUsersChanging(AspNetUsers value);
        /// <summary>Called after <see cref="UserAspNetUsers"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnUserAspNetUsersChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspNetUserRoles"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="AspNetUserRoles"/> instance.</param>
        /// <returns>An instance of <see cref="AspNetUserRoles"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static AspNetUserRoles FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspNetUserRoles));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as AspNetUserRoles;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspNetUserRoles"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="AspNetUserRoles"/> instance.</param>
        /// <returns>An instance of <see cref="AspNetUserRoles"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static AspNetUserRoles FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspNetUserRoles));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as AspNetUserRoles;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public AspNetUserRoles Clone()
        {
            return (AspNetUserRoles)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _roleAspNetRoles = Detach(_roleAspNetRoles);
            _userAspNetUsers = Detach(_userAspNetUsers);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
