#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace SmartSocial.Data
{
    /// <summary>
    /// The class representing the dbo.Country table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.Country")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(SmartSocial.Data.Country.Metadata))]
    [System.Data.Services.Common.DataServiceKey("IdCountry")]
    [System.Diagnostics.DebuggerDisplay("IdCountry: {IdCountry}")]
    public partial class Country
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="Country"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static Country()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Country"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Country()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _idCountry;

        /// <summary>
        /// Gets or sets the IdCountry column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdCountry", Storage = "_idCountry", DbType = "int NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int IdCountry
        {
            get { return _idCountry; }
            set
            {
                if (_idCountry != value)
                {
                    OnIdCountryChanging(value);
                    SendPropertyChanging("IdCountry");
                    _idCountry = value;
                    SendPropertyChanged("IdCountry");
                    OnIdCountryChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _iso2;

        /// <summary>
        /// Gets or sets the ISO2 column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ISO2", Storage = "_iso2", DbType = "char(2)")]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string Iso2
        {
            get { return _iso2; }
            set
            {
                if (_iso2 != value)
                {
                    OnIso2Changing(value);
                    SendPropertyChanging("Iso2");
                    _iso2 = value;
                    SendPropertyChanged("Iso2");
                    OnIso2Changed();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _countryName;

        /// <summary>
        /// Gets or sets the CountryName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "CountryName", Storage = "_countryName", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string CountryName
        {
            get { return _countryName; }
            set
            {
                if (_countryName != value)
                {
                    OnCountryNameChanging(value);
                    SendPropertyChanging("CountryName");
                    _countryName = value;
                    SendPropertyChanged("CountryName");
                    OnCountryNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _longCountryName;

        /// <summary>
        /// Gets or sets the LongCountryName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "LongCountryName", Storage = "_longCountryName", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string LongCountryName
        {
            get { return _longCountryName; }
            set
            {
                if (_longCountryName != value)
                {
                    OnLongCountryNameChanging(value);
                    SendPropertyChanging("LongCountryName");
                    _longCountryName = value;
                    SendPropertyChanged("LongCountryName");
                    OnLongCountryNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _iso3;

        /// <summary>
        /// Gets or sets the ISO3 column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ISO3", Storage = "_iso3", DbType = "char(3)")]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string Iso3
        {
            get { return _iso3; }
            set
            {
                if (_iso3 != value)
                {
                    OnIso3Changing(value);
                    SendPropertyChanging("Iso3");
                    _iso3 = value;
                    SendPropertyChanged("Iso3");
                    OnIso3Changed();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _numCode;

        /// <summary>
        /// Gets or sets the NumCode column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "NumCode", Storage = "_numCode", DbType = "nvarchar(6)")]
        [System.ComponentModel.DataAnnotations.StringLength(6)]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string NumCode
        {
            get { return _numCode; }
            set
            {
                if (_numCode != value)
                {
                    OnNumCodeChanging(value);
                    SendPropertyChanging("NumCode");
                    _numCode = value;
                    SendPropertyChanged("NumCode");
                    OnNumCodeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _uNMemberState;

        /// <summary>
        /// Gets or sets the UNMemberState column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "UNMemberState", Storage = "_uNMemberState", DbType = "nvarchar(12)")]
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string UNMemberState
        {
            get { return _uNMemberState; }
            set
            {
                if (_uNMemberState != value)
                {
                    OnUNMemberStateChanging(value);
                    SendPropertyChanging("UNMemberState");
                    _uNMemberState = value;
                    SendPropertyChanged("UNMemberState");
                    OnUNMemberStateChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _callingCode;

        /// <summary>
        /// Gets or sets the CallingCode column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "CallingCode", Storage = "_callingCode", DbType = "nvarchar(8)")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        [System.Runtime.Serialization.DataMember(Order = 8)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string CallingCode
        {
            get { return _callingCode; }
            set
            {
                if (_callingCode != value)
                {
                    OnCallingCodeChanging(value);
                    SendPropertyChanging("CallingCode");
                    _callingCode = value;
                    SendPropertyChanged("CallingCode");
                    OnCallingCodeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _cctld;

        /// <summary>
        /// Gets or sets the CCTLD column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "CCTLD", Storage = "_cctld", DbType = "nvarchar(5)")]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        [System.Runtime.Serialization.DataMember(Order = 9)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string Cctld
        {
            get { return _cctld; }
            set
            {
                if (_cctld != value)
                {
                    OnCctldChanging(value);
                    SendPropertyChanging("Cctld");
                    _cctld = value;
                    SendPropertyChanged("Cctld");
                    OnCctldChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _flagImageFilename;

        /// <summary>
        /// Gets or sets the FlagImageFilename column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "FlagImageFilename", Storage = "_flagImageFilename", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 10)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string FlagImageFilename
        {
            get { return _flagImageFilename; }
            set
            {
                if (_flagImageFilename != value)
                {
                    OnFlagImageFilenameChanging(value);
                    SendPropertyChanging("FlagImageFilename");
                    _flagImageFilename = value;
                    SendPropertyChanged("FlagImageFilename");
                    OnFlagImageFilenameChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="IdCountry"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdCountryChanging(int value);
        /// <summary>Called after <see cref="IdCountry"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdCountryChanged();
        /// <summary>Called when <see cref="Iso2"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIso2Changing(string value);
        /// <summary>Called after <see cref="Iso2"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIso2Changed();
        /// <summary>Called when <see cref="CountryName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCountryNameChanging(string value);
        /// <summary>Called after <see cref="CountryName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCountryNameChanged();
        /// <summary>Called when <see cref="LongCountryName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLongCountryNameChanging(string value);
        /// <summary>Called after <see cref="LongCountryName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLongCountryNameChanged();
        /// <summary>Called when <see cref="Iso3"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIso3Changing(string value);
        /// <summary>Called after <see cref="Iso3"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIso3Changed();
        /// <summary>Called when <see cref="NumCode"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnNumCodeChanging(string value);
        /// <summary>Called after <see cref="NumCode"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnNumCodeChanged();
        /// <summary>Called when <see cref="UNMemberState"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnUNMemberStateChanging(string value);
        /// <summary>Called after <see cref="UNMemberState"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnUNMemberStateChanged();
        /// <summary>Called when <see cref="CallingCode"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCallingCodeChanging(string value);
        /// <summary>Called after <see cref="CallingCode"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCallingCodeChanged();
        /// <summary>Called when <see cref="Cctld"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCctldChanging(string value);
        /// <summary>Called after <see cref="Cctld"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCctldChanged();
        /// <summary>Called when <see cref="FlagImageFilename"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnFlagImageFilenameChanging(string value);
        /// <summary>Called after <see cref="FlagImageFilename"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnFlagImageFilenameChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Country"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Country"/> instance.</param>
        /// <returns>An instance of <see cref="Country"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Country FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Country));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as Country;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Country"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Country"/> instance.</param>
        /// <returns>An instance of <see cref="Country"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Country FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Country));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as Country;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Country Clone()
        {
            return (Country)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
