#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace SmartSocial.Data
{
    /// <summary>
    /// The class representing the dbo.UsersXSubscription table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.UsersXSubscription")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(SmartSocial.Data.UsersXSubscription.Metadata))]
    [System.Data.Services.Common.DataServiceKey("IdSubscription", "IdUser")]
    [System.Diagnostics.DebuggerDisplay("IdSubscription: {IdSubscription}, IdUser: {IdUser}")]
    public partial class UsersXSubscription
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="UsersXSubscription"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static UsersXSubscription()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="UsersXSubscription"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public UsersXSubscription()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            _idSubscriptionServiceSubscription = default(System.Data.Linq.EntityRef<ServiceSubscription>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _idSubscription;

        /// <summary>
        /// Gets or sets the idSubscription column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "idSubscription", Storage = "_idSubscription", DbType = "int NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int IdSubscription
        {
            get { return _idSubscription; }
            set
            {
                if (_idSubscription != value)
                {
                    if (_idSubscriptionServiceSubscription.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdSubscriptionChanging(value);
                    SendPropertyChanging("IdSubscription");
                    _idSubscription = value;
                    SendPropertyChanged("IdSubscription");
                    OnIdSubscriptionChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _idUser;

        /// <summary>
        /// Gets or sets the idUser column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "idUser", Storage = "_idUser", DbType = "nvarchar(128) NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string IdUser
        {
            get { return _idUser; }
            set
            {
                if (_idUser != value)
                {
                    OnIdUserChanging(value);
                    SendPropertyChanging("IdUser");
                    _idUser = value;
                    SendPropertyChanged("IdUser");
                    OnIdUserChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private Nullable<System.DateTime> _dateCreated;

        /// <summary>
        /// Gets or sets the DateCreated column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "DateCreated", Storage = "_dateCreated", DbType = "datetime")]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Nullable<System.DateTime> DateCreated
        {
            get { return _dateCreated; }
            set
            {
                if (_dateCreated != value)
                {
                    OnDateCreatedChanging(value);
                    SendPropertyChanging("DateCreated");
                    _dateCreated = value;
                    SendPropertyChanged("DateCreated");
                    OnDateCreatedChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<ServiceSubscription> _idSubscriptionServiceSubscription;

        /// <summary>
        /// Gets or sets the <see cref="ServiceSubscription"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "ServiceSubscription_UsersXSubscription", Storage = "_idSubscriptionServiceSubscription", ThisKey = "IdSubscription", OtherKey = "IdServiceSubscription", IsForeignKey = true, DeleteRule = "CASCADE")]
        [System.Runtime.Serialization.DataMember(Order = 4, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ServiceSubscription IdSubscriptionServiceSubscription
        {
            get { return (serializing && !_idSubscriptionServiceSubscription.HasLoadedOrAssignedValue) ? null : _idSubscriptionServiceSubscription.Entity; }
            set
            {
                ServiceSubscription previousValue = _idSubscriptionServiceSubscription.Entity;
                if (previousValue != value || _idSubscriptionServiceSubscription.HasLoadedOrAssignedValue == false)
                {
                    OnIdSubscriptionServiceSubscriptionChanging(value);
                    SendPropertyChanging("IdSubscriptionServiceSubscription");
                    if (previousValue != null)
                    {
                        _idSubscriptionServiceSubscription.Entity = null;
                        previousValue.IdSubscriptionUsersXSubscriptionList.Remove(this);
                    }
                    _idSubscriptionServiceSubscription.Entity = value;
                    if (value != null)
                    {
                        value.IdSubscriptionUsersXSubscriptionList.Add(this);
                        _idSubscription = value.IdServiceSubscription;
                    }
                    else
                    {
                        _idSubscription = default(int);
                    }
                    SendPropertyChanged("IdSubscriptionServiceSubscription");
                    OnIdSubscriptionServiceSubscriptionChanged();
                }
            }
        }
        
        
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="IdSubscription"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSubscriptionChanging(int value);
        /// <summary>Called after <see cref="IdSubscription"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSubscriptionChanged();
        /// <summary>Called when <see cref="IdUser"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdUserChanging(string value);
        /// <summary>Called after <see cref="IdUser"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdUserChanged();
        /// <summary>Called when <see cref="DateCreated"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDateCreatedChanging(Nullable<System.DateTime> value);
        /// <summary>Called after <see cref="DateCreated"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDateCreatedChanged();
        /// <summary>Called when <see cref="IdSubscriptionServiceSubscription"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSubscriptionServiceSubscriptionChanging(ServiceSubscription value);
        /// <summary>Called after <see cref="IdSubscriptionServiceSubscription"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSubscriptionServiceSubscriptionChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="UsersXSubscription"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="UsersXSubscription"/> instance.</param>
        /// <returns>An instance of <see cref="UsersXSubscription"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static UsersXSubscription FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(UsersXSubscription));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as UsersXSubscription;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="UsersXSubscription"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="UsersXSubscription"/> instance.</param>
        /// <returns>An instance of <see cref="UsersXSubscription"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static UsersXSubscription FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(UsersXSubscription));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as UsersXSubscription;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public UsersXSubscription Clone()
        {
            return (UsersXSubscription)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _idSubscriptionServiceSubscription = Detach(_idSubscriptionServiceSubscription);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
