//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSocialServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartSocialServices.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8]&gt;&lt;html class=&quot;no-js lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;!-- Mobile specific metas --&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no&quot;&gt;
        ///        &lt;!-- Force IE9 to render in normal mode --&gt;
        ///        &lt;!--[if IE]&gt;&lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=9&quot; /&gt;&lt;![endif]--&gt;
        ///        &lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        ///        &lt;me [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AccountInvitation {
            get {
                return ResourceManager.GetString("AccountInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8]&gt;&lt;html class=&quot;no-js lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!-- Mobile specific metas --&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no&quot;&gt;
        ///    &lt;!-- Force IE9 to render in normal mode --&gt;
        ///    &lt;!--[if IE]&gt;&lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=9&quot; /&gt;&lt;![endif]--&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8]&gt;&lt;html class=&quot;no-js lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;!-- Mobile specific metas --&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no&quot;&gt;
        ///        &lt;!-- Force IE9 to render in normal mode --&gt;
        ///        &lt;!--[if IE]&gt;&lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=9&quot; /&gt;&lt;![endif]--&gt;
        ///        &lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        ///        &lt;me [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IntakeConfirmation {
            get {
                return ResourceManager.GetString("IntakeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8]&gt;&lt;html class=&quot;no-js lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;!-- Mobile specific metas --&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no&quot;&gt;
        ///        &lt;!-- Force IE9 to render in normal mode --&gt;
        ///        &lt;!--[if IE]&gt;&lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=9&quot; /&gt;&lt;![endif]--&gt;
        ///        &lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        ///        &lt;meta name=&quot;de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeadConfirmation {
            get {
                return ResourceManager.GetString("LeadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartsocial@appverified.com.
        /// </summary>
        public static string NoReplyEmail {
            get {
                return ResourceManager.GetString("NoReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monteran00!.
        /// </summary>
        public static string NoReplyPassword {
            get {
                return ResourceManager.GetString("NoReplyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=&apos;SmartSocialVM.cloudapp.net&apos;;Initial Catalog=SmartSocial_QA;Persist Security Info=True;User ID=SmartSocialApp;Password=Monteran00!.
        /// </summary>
        public static string Sproc {
            get {
                return ResourceManager.GetString("Sproc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8]&gt;&lt;html class=&quot;no-js lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!-- Mobile specific metas --&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no&quot;&gt;
        ///    &lt;!-- Force IE9 to render in normal mode --&gt;
        ///    &lt;!--[if IE]&gt;&lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=9&quot; /&gt;&lt;![endif]--&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubscritionAdded {
            get {
                return ResourceManager.GetString("SubscritionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8]&gt;&lt;html class=&quot;no-js lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!-- Mobile specific metas --&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no&quot;&gt;
        ///    &lt;!-- Force IE9 to render in normal mode --&gt;
        ///    &lt;!--[if IE]&gt;&lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=9&quot; /&gt;&lt;![endif]--&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubscritionInvitation {
            get {
                return ResourceManager.GetString("SubscritionInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string TopN {
            get {
                return ResourceManager.GetString("TopN", resourceCulture);
            }
        }
    }
}
